// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhanVien.API.Models;

namespace QuanLyNhanVien.API.Migrations.SQLiteMigrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("QuanLyNhanVien.API.Models.Cityprovince", b =>
                {
                    b.Property<int>("IdCityProvince")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idCityProvince")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(45);

                    b.HasKey("IdCityProvince");

                    b.ToTable("cityprovince");
                });

            modelBuilder.Entity("QuanLyNhanVien.API.Models.Employees", b =>
                {
                    b.Property<int>("IdEmployees")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idEmployees")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityDistrict")
                        .HasColumnType("TEXT")
                        .HasMaxLength(45);

                    b.Property<string>("CityProvince")
                        .HasColumnType("TEXT")
                        .HasMaxLength(45);

                    b.Property<string>("Country")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(40);

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasMaxLength(45);

                    b.Property<string>("TitleOfCourtesy")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.HasKey("IdEmployees");

                    b.ToTable("employees");
                });
#pragma warning restore 612, 618
        }
    }
}
